apiVersion: v1
kind: Pod
metadata:
  name: l2r-env-old
spec:
  containers:
  - env:
    image: docker.pdl.cmu.edu/jingyua4/safepo:v1
    # command:
    #   - /bin/bash
    #   - -c
    #   - cd / &&
    #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC &&
    #     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC &&
    #     sudo apt-get update &&
    #     sudo apt-get install -y python3.8 python3.8-dev python3.8-distutils python3.8-venv &&
    #     wget https://bootstrap.pypa.io/get-pip.py &&
    #     sudo python3.8 get-pip.py &&
    #     apt install -y git &&
    #     git clone https://github.com/Anirudh-Kannan/l2r-lab.git &&
    #     cd l2r-distributed &&
    #     git checkout l2r-sequential &&
    #     pip install git+https://github.com/learn-to-race/l2r@aicrowd-environment &&
    #     pip install -r setup/devtools_reqs.txt &&
    #     pip install "opencv-python-headless<4.3" protobuf==3.20.* &&
    #     cd /home/LinuxNoEditor/
    name: learner-container
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /mnt
      name: l2r-volume
    resources: 
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    kubernetes.io/hostname: phortx2
  restartPolicy: Never
  volumes:
  - name: l2r-volume
    persistentVolumeClaim:
            claimName: l2r-persistent-claim
