experiment_config:
  experiment_name: 'SAC-test'
  inference_only: False
  load_checkpoint: False
  record_experience: False

encoder_kwargs:
  encoder_type: 'vae'
  chkpt_location: 'l2r/common/models/vae_144w_42h_32latent.pth'
  latent_dims: 32
  hiddens: [32, 64, 64, 32, 32]
  speed_hiddens:  [8, 8]
  actor_hiddens: [64, 64, 32]
  im_c: 3
  im_w: 144
  im_h: 42
  ac_input_dims: 32 
  include_speed: 1     # encoder_switch: 1

agent_kwargs:
    make_random_actions: 0
    gamma: 0.99
    polyak: 0.995
    lr: 0.003
    alpha: 0.2
    batch_size: 256
    steps_to_sample_randomly: 2000 # start_steps
    checkpoint: 'models/sac/checkpoints/best_sac_local_encoder-vae_small_seed-249_episode_480.statedict'
    model_save_path: '${PREFIX}/l2r/results/${DIRHASH}workspaces/${USER}/results'

runner_kwargs:
  model_save_dir: '${PREFIX}/l2r/results/${DIRHASH}workspaces/${USER}/results'
  experience_save_dir: '${PREFIX}/l2r/datasets/l2r/datasets/safety_records_dataset/'
  num_test_episodes: 1
  save_every_nth_episode: 1
  total_environment_steps: 250_000
  update_model_after: 2000 # update_after steps
  update_model_every: 1 # update_every
  eval_every: 5000
  max_episode_length: 50000 # max_ep_len

env_kwargs:
  track_name: 'Thruxton'
  runtime: local
  dirhash: ''

replay_buffer_kwargs:
  replay_size: 250_000